### PR TITLE
Cleaned up console.log messages from JS

### PR DESCRIPTION
**Pull request by nathanrmair**
For issue #9

### CODE REVIEW

**Comment by nathanrmair** [comment]
Also fixed merge nodes remaining in context menu after a node merge is carried out, issue #6

**Comment by siwells** [comment]
Sorry, didn't notice your PR but I have fixed most of these already in the latest codebase. Feel free to take a look at the deployment here: [http://arg.napier.ac.uk/monkeypuzzle/](http://arg.napier.ac.uk/monkeypuzzle/)

**Comment by nathanrmair** [comment]
No worries, updates look fantastic, I'm at work so can't do this right now, but noticed that the slideout in the html tag is overflowing which causes scrolling issues within the slideout tab, I think I remember this being a problem when I was working on it but it seems you can just hide the overflow within the html tag. Feel free to delete this comment if it's inappropriate for the thread!

**Comment by siwells** [comment]
Thanks. I've been pushing to get towards a verions 1.0 release. Focussing on a consistent and sensible user experience, and reliable functionality. I also refactored a fair amount of the code for clarity so that [1] any new students working on this have a codebase that is easier to work with, and [2] other research groups can easily extend the core functionality to help them answer their own research questions.

Feel free to create issues, bug fix, or sanity check my ideas.... Once you're home from work of course...

**Pull request closed without merging**
